server:
  port: 8701
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  application:
    name: SqlToCode
  main:
    banner-mode: off
    # stdio 模式打开，sse 模式，注释掉。
    # web-application-type: none
  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: 1.0.0
        type: ASYNC
        instructions: "This server provides sql to code  tools "
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true

logging:
  # stdio 模式打开，sse 模式，注释掉。
  #  pattern:
  #    console:
  file:
    name: data/log/${spring.application.name}.log


